files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/Zavrsni_v3_1
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: 00D7A26D402F793CAE1D2D7018877711
  logicalPath: config/Zavrsni_v3_1
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 00D7A26D402F793CAE1D2D7018877711
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config/Zavrsni_v3_1
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: F81A00E640818EDFB9E79C9BD241AEF4
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: F81A00E640818EDFB9E79C9BD241AEF4
- generatedChecksum: ECACFD77278C4CF0474FDC8B1B49DBC9
  logicalPath: config/Zavrsni_v3_1/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: ECACFD77278C4CF0474FDC8B1B49DBC9
- generatedChecksum: ED6722C1169FEA2DA1F15D907F42AA46
  logicalPath: config/Zavrsni_v3_1/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED6722C1169FEA2DA1F15D907F42AA46
- generatedChecksum: 3D67EFD79A695D83A151CCF115D45DC5
  logicalPath: config/Zavrsni_v3_1/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3D67EFD79A695D83A151CCF115D45DC5
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/Zavrsni_v3_1/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: D87F97F61F02CE00FB805C95D75191EB
  logicalPath: config/Zavrsni_v3_1
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: D87F97F61F02CE00FB805C95D75191EB
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/Zavrsni_v3_1
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/Zavrsni_v3_1
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/Zavrsni_v3_1/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 815CCB981B6CB758464D89480121DC08
  logicalPath: config/Zavrsni_v3_1/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 815CCB981B6CB758464D89480121DC08
- generatedChecksum: 4C730E56D028FBC00572DDBD3E67C7C7
  logicalPath: config/Zavrsni_v3_1/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C730E56D028FBC00572DDBD3E67C7C7
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/Zavrsni_v3_1
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: 07A482DAB7473FC475EA656561967B15
  logicalPath: config/Zavrsni_v3_1
  name: p32MZ2048EFM144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 07A482DAB7473FC475EA656561967B15
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/Zavrsni_v3_1;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/Zavrsni_v3_1;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
